networks:
  cli-commerce-parser:
    name: cli-commerce-parser

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cli-commerce-parser

  php:
    build:
      context: ./docker/php
      dockerfile: php-fpm.dockerfile
    container_name: php
    environment:
      DB_HOST: mysql
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9005:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cli-commerce-parser

  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - cli-commerce-parser

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: [5672, 15672]
    networks:
      - cli-commerce-parser

volumes:
  mysql_data: